name: Deploy
# This workflow is triggered on pushes to the repository.
on: [push]
    
defaults:
  run:
    working-directory: ./api

jobs:
 install:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v1
   - run: ls
   - uses: actions-hub/gcloud@master
     env:
          PROJECT_ID: pisspricer
          APPLICATION_CREDENTIALS: ${{secrets.GKE_SA_KEY}}
     with:
          args: app deploy app.yml
   - run: ls 
          
          

